Title: Project

columns:
  - width: 1/2
    sections:
      content:
        type: fields
        fields:
          text:
            headline: Text
            type: textarea
            size: large
      media:
        type: files
        headline: Media
        empty: "No media yet"
        layout: cards
        template: media
  - width: 1/2
    sections:
      info:
        type: fields
        fields:
          dateCompleted:
            type: date
            label: Date completed
            min: 1980-01-01
          data:
            type: structure
            label: Data
            columns:
              label:
                width: 1/3
              text:
                width: 2/3
            fields:
              label:
                label: Label
                type: text
              text:
                label: Text
                type: text
